# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Cronograma"
  url = "#timetable"
  weight = 20

[[main]]
  name = "Programa"
  url = "#syllabus"
  weight = 40
  
[[main]]
  name = "Tópicos"
  url = "#schedule"
  weight = 50

[[main]]
  name = "Ajuda"
  url = "#help"
  weight = 60
  
#[[main]]
#  name = "Extra credit"
#  url = "#extra"
#  weight = 61

#[[main]]
#  name = "Project"
#  url = "#project"
#  weight = 70

[[main]]
  name = "Recursos"
  url = "#resources"
  weight = 80
  
[[main]]
  name = "Staff"
  url = "#people"
  weight = 90
  
[[main]]
  name = "<i class='fab fa-youtube'></i>"
  url = "https://www.youtube.com/channel/UCipdvs6ziGfaCSN1yeIKNKw"
  weight = 100
  
[[main]]
  name = "<i class='fab fa-keybase'></i>"
  url = "https://keybase.io/team/r_basicox"
  weight = 110
  menu_align_right = true

[[main]]
  name = "<i class='fab fa-r-project'></i>"
  url = "https://rstudio.cloud"
  weight = 120


[[main]]
  name = "<i class='fab fa-github'></i>"
  url = "https://www.learn.ed.ac.uk/"
  weight = 130
  menu_align_right = true
